.gitignore

Intento para evitar conflictos definitivo

Agregado git ignore final

---

SW1_ISO9126_FUZZY/InferenciaDifusa/InferenciaDifusa.cs
SW1_ISO9126_FUZZY/Logica Difusa/Funciones Membresia/FuncionMembresia.cs
SW1_ISO9126_FUZZY/Logica Difusa/ImplicacionDifusa.cs
SW1_ISO9126_FUZZY/Logica Difusa/ReglaDifusa.cs
SW1_ISO9126_FUZZY/Logica Difusa/ValorLinguistico.cs
SW1_ISO9126_FUZZY/Logica Difusa/VariableLinguistica.cs
SW1_ISO9126_FUZZY/SW1_ISO9126_FUZZY.csproj

Se agregaron las clases que faltaban:
- Funciones de Membresia
- Implicacion difusa
- Regla difusa
- Valor lingüístico
- Variable lingüística
Se creó el módulo y la clase para realizar el proceso de inferencia difusa:
- Inferencia Difusa

Se completó el modulo de Logica Difusa y el modulo Inferencia

---

.gitignore
SW1_ISO9126_FUZZY/App.xaml
SW1_ISO9126_FUZZY/MainWindow.xaml
SW1_ISO9126_FUZZY/MainWindow.xaml.cs
SW1_ISO9126_FUZZY/Vistas/MainPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/RegistroSWPage.xaml
SW1_ISO9126_FUZZY/Vistas/RegistroSWPage.xaml.cs

Validada interfaz de datos del software y grados de importancia
Agregada configuracion de estilo ventanas de mensajes

Menu software funcionalidad

---

SW1_ISO9126_FUZZY/App.xaml
SW1_ISO9126_FUZZY/Vistas/FormEvaluacionPage.xaml
SW1_ISO9126_FUZZY/Vistas/FormEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/RegistroSWPage.xaml
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml

Mejorado estilos letras en negrita en las paginas
casi finalizada gui formulario evaluación

Formulario evaluacion

---

SW1_ISO9126_FUZZY/Vistas/EvaluacionCalidadPage.xaml

Agregada seccion configuracion PDF en calidad final
Agregada seccion datos reporte en calidad final

Gui evaluacion final

---

SW1_ISO9126_FUZZY/Vistas/EvaluacionCalidadPage.xaml
SW1_ISO9126_FUZZY/Vistas/EvaluacionCalidadPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/RegistroSWPage.xaml
SW1_ISO9126_FUZZY/Vistas/RegistroSWPage.xaml.cs

Validado botones gui calidad final
Corregido aspectos visuales
Coregido estrutura del codigo botones movimiento pestañas

Validar gui nivel calidad final

---

SW1_ISO9126_FUZZY/Archivos_configuracion/FuncionalidadExterna.json
SW1_ISO9126_FUZZY/Archivos_configuracion/FuncionalidadInterna.json
SW1_ISO9126_FUZZY/Archivos_configuracion/JRevisar.cs
SW1_ISO9126_FUZZY/Archivos_configuracion/MantenibilidadExterna.json
SW1_ISO9126_FUZZY/Archivos_configuracion/MantenibilidadInterna.json
SW1_ISO9126_FUZZY/Archivos_configuracion/UsabilidadExterna.json
SW1_ISO9126_FUZZY/Archivos_configuracion/UsabilidadInterna.json
SW1_ISO9126_FUZZY/JSON/JMetrica.cs
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml.cs

Creados archivos finales metricas
Cargada subcaracteristica metrica a traves de un atributo subcaracteristica.

Cargar metricas

---

SW1_ISO9126_FUZZY/Evaluacion Calidad/Tercer Nivel Calidad Final/Reglas Produccion/ReglasCalidadExterna.cs
SW1_ISO9126_FUZZY/Evaluacion Calidad/Tercer Nivel Calidad Final/Reglas Produccion/ReglasCalidadInterna.cs
SW1_ISO9126_FUZZY/Evaluacion Calidad/Tercer Nivel Calidad Final/Valores Linguisticos/ValoresCalidadExterna.cs
SW1_ISO9126_FUZZY/Evaluacion Calidad/Tercer Nivel Calidad Final/Valores Linguisticos/ValoresCalidadInterna.cs
SW1_ISO9126_FUZZY/Evaluacion Calidad/Tercer Nivel Calidad Final/Variables Linguisticas/VariablesCalidadExterna.cs
SW1_ISO9126_FUZZY/Evaluacion Calidad/Tercer Nivel Calidad Final/Variables Linguisticas/VariablesCalidadInterna.cs
SW1_ISO9126_FUZZY/Inferencia Difusa/Inferencia.cs
SW1_ISO9126_FUZZY/SW1_ISO9126_FUZZY.csproj

- Se agregó la carpeta con el Tercer Nivel de Calidad y las subcarpetas

Se corrigieron las referencias en la carpeta Evaluación Calidad

---

SW1_ISO9126_FUZZY/Vistas/FormEvaluacionPage.xaml
SW1_ISO9126_FUZZY/Vistas/FormEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml.cs

Cargados parametros en formulario evaluación, metodo de carga de una metrica.
Mejorado tamaños y visualizacion de carga en seleccion de metricas en los parametros.

Cargar parametros evaluacion metricas

---

SW1_ISO9126_FUZZY/Vistas/FormEvaluacionPage.xaml
SW1_ISO9126_FUZZY/Vistas/FormEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/FormularioEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml.cs

Agregado metodo para cambiar los estados de las metricas
Corregido scrollview no funcionales

Colores estados

---

SW1_ISO9126_FUZZY/App.xaml
SW1_ISO9126_FUZZY/Vistas/FormularioEvaluacionPage.xaml
SW1_ISO9126_FUZZY/Vistas/FormularioEvaluacionPage.xaml.cs

Agregado medalla (badge) para el ver el estado de vanace de la evaluación

Btn notificacion

---

SW1_ISO9126_FUZZY/Logica Difusa/AgregacionReglas.cs
SW1_ISO9126_FUZZY/Logica Difusa/Funciones Membresia/FuncionMembresia.cs
SW1_ISO9126_FUZZY/Logica Difusa/Funciones Membresia/FuncionMembresiaTrapezoidal.cs
SW1_ISO9126_FUZZY/Logica Difusa/Funciones Membresia/FuncionMembresiaTriangular.cs
SW1_ISO9126_FUZZY/Logica Difusa/Funciones Membresia/IFuncionMembresia.cs
SW1_ISO9126_FUZZY/Logica Difusa/ImplicacionDifusa.cs
SW1_ISO9126_FUZZY/SW1_ISO9126_FUZZY.csproj

- Se añadieron métodos que faltaban

Se corrigieron errores de implementación

---

SW1_ISO9126_FUZZY/Archivos_configuracion/Test_JMetricas.cs
SW1_ISO9126_FUZZY/Modelo Datos/Calculo.cs
SW1_ISO9126_FUZZY/Modelo Datos/EstadoFinal.cs
SW1_ISO9126_FUZZY/Modelo Datos/EstadoModulo.cs
SW1_ISO9126_FUZZY/Modelo Datos/Evaluacion.cs
SW1_ISO9126_FUZZY/Modelo Datos/Importancia.cs
SW1_ISO9126_FUZZY/Modelo Datos/Respuesta.cs
SW1_ISO9126_FUZZY/Modelo Datos/Seleccion.cs
SW1_ISO9126_FUZZY/Modelo Datos/Software.cs
SW1_ISO9126_FUZZY/SW1_ISO9126_FUZZY.csproj

Agregas clases para el manejo del flujo de la aplicación (interaccion entre componentes) y para guardar el estado en un archivo final.

Clases datos base

---

SW1_ISO9126_FUZZY/Archivos_configuracion/JRevisar.cs
SW1_ISO9126_FUZZY/Inferencia Difusa/Inferencia.cs
SW1_ISO9126_FUZZY/Logica Difusa/AgregacionReglas.cs
SW1_ISO9126_FUZZY/Logica Difusa/DefuzzificacionCentroide.cs
SW1_ISO9126_FUZZY/Logica Difusa/Funciones Membresia/FuncionMembresiaTrapezoidal.cs
SW1_ISO9126_FUZZY/Logica Difusa/Funciones Membresia/FuncionMembresiaTriangular.cs
SW1_ISO9126_FUZZY/Logica Difusa/ImplicacionDifusa.cs
SW1_ISO9126_FUZZY/Logica Difusa/ReglaDifusa.cs
SW1_ISO9126_FUZZY/Logica Difusa/ValorLinguistico.cs
SW1_ISO9126_FUZZY/Logica Difusa/VariableLinguistica.cs

- Se corrigieron errores de variables y varios.

Se revisó todo el módulo de Fuzzy de nuevo

---

SW1_ISO9126_FUZZY/Archivos_configuracion/JRevisar.cs
SW1_ISO9126_FUZZY/Archivos_configuracion/MantenibilidadExterna.json
SW1_ISO9126_FUZZY/Archivos_configuracion/UsabilidadExterna.json
SW1_ISO9126_FUZZY/Evaluacion Calidad/Calculos/Formula.cs
SW1_ISO9126_FUZZY/Evaluacion Calidad/Calculos/Normalizacion.cs
SW1_ISO9126_FUZZY/Evaluacion Calidad/Calculos/Ponderacion.cs
SW1_ISO9126_FUZZY/SW1_ISO9126_FUZZY.csproj

- Normalización de los grados de importancia
- Ponderación de los datos.
- Fórmula de las métricas
- Se modificaron los archivos Json MantenibilidadExterna y Usabilidad Externa y se corrigieron los índices.

Se generaron las clases para los cálculos previos al Modulo Fuzzy

---

SW1_ISO9126_FUZZY/Vistas/MainPage.xaml.cs

Validada y activada carga archivo JSON

Datos paginaprincipal

---

SW1_ISO9126_FUZZY/MainWindow.xaml
SW1_ISO9126_FUZZY/MainWindow.xaml.cs
SW1_ISO9126_FUZZY/Modelo Datos/Evaluacion.cs
SW1_ISO9126_FUZZY/Vistas/EvaluacionCalidadPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/FormEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/FormularioEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/MainPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/RegistroSWPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml.cs

Finalizado el modelo de flujo de datos, para paginas principales.

Modelo flujo datos

---

SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml

Estandarizados componentes gui
Mejorado aspecto visual

Vista previa seleccion

---

SW1_ISO9126_FUZZY/Vistas/EvaluacionCalidadPage.xaml
SW1_ISO9126_FUZZY/Vistas/FormEvaluacionPage.xaml
SW1_ISO9126_FUZZY/Vistas/FormEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/FormularioEvaluacionPage.xaml
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml.cs

Mejora aspectos visuales en seleccion de metricas
Limpieza de codigo, parametro innecesario
Corregido error slider

Mejora gui

---

SW1_ISO9126_FUZZY/JSON/JFuncionabilidad.cs
SW1_ISO9126_FUZZY/JSON/JMantenibilidad.cs
SW1_ISO9126_FUZZY/JSON/JUsabilidad.cs
SW1_ISO9126_FUZZY/Modelo Datos/MTEvaluacion.cs
SW1_ISO9126_FUZZY/Modelo Datos/MTSeleccion.cs
SW1_ISO9126_FUZZY/Properties/AssemblyInfo.cs
SW1_ISO9126_FUZZY/SW1_ISO9126_FUZZY.csproj
SW1_ISO9126_FUZZY/Vistas/FormEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml.cs

Creada clases bases para almacenar seleccion
Creadas listas externas y lista interna para guardar la seleccion
Optimizado metodo de lectura de metricas desde JSON
Limpieza de codigo en seleccion de metricas
Creados metodos de guardar, comprobar estado seleccion
Mejorado metodo carga menu de metricas

Lista seleccion de metricas

---

SW1_ISO9126_FUZZY/App.xaml
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml.cs

Unificada lista metricas
Conexion lista metricas con seleccion de metricas

Opt selec metric

---

SW1_ISO9126_FUZZY/App.xaml
SW1_ISO9126_FUZZY/MainWindow.xaml.cs
SW1_ISO9126_FUZZY/Vistas/FormularioEvaluacionPage.xaml
SW1_ISO9126_FUZZY/Vistas/MainPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml.cs

Agregado el modelo a la pagina de inicio
Agregado cosas varias

Modelo pagina inicio

---

SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml.cs

Detalles seleccion metricas

---

SW1_ISO9126_FUZZY/Archivos_configuracion/FuncionalidadExterna.json
SW1_ISO9126_FUZZY/Archivos_configuracion/MantenibilidadExterna.json
SW1_ISO9126_FUZZY/Archivos_configuracion/UsabilidadExterna.json

Habías dos métricas no correspondientes.

Se corrigieron id's y archivo funcionalidad externa

---

SW1_ISO9126_FUZZY/App.xaml
SW1_ISO9126_FUZZY/Archivos_configuracion/MantenibilidadExterna.json
SW1_ISO9126_FUZZY/Evaluacion Calidad/Calculos/Formula.cs
SW1_ISO9126_FUZZY/Modelo Datos/Importancias/ISCFuncionalidad.cs
SW1_ISO9126_FUZZY/Modelo Datos/Importancias/ISCMantenibilidad.cs
SW1_ISO9126_FUZZY/Modelo Datos/Importancias/ISCUsabilidad.cs
SW1_ISO9126_FUZZY/Modelo Datos/Importancias/Importancia.cs
SW1_ISO9126_FUZZY/Modelo Datos/Listas/ListCalculo.cs
SW1_ISO9126_FUZZY/Modelo Datos/Listas/ListEvaluacion.cs
SW1_ISO9126_FUZZY/Modelo Datos/Listas/ListMetrica.cs
SW1_ISO9126_FUZZY/Modelo Datos/Listas/ListSeleccion.cs
SW1_ISO9126_FUZZY/Modelo Datos/Listas/MTCalculo.cs
SW1_ISO9126_FUZZY/Modelo Datos/Listas/MTEvaluacion.cs
SW1_ISO9126_FUZZY/Modelo Datos/Listas/MTSeleccion.cs
SW1_ISO9126_FUZZY/Vistas/EvaluacionCalidadPage.xaml
SW1_ISO9126_FUZZY/Vistas/EvaluacionCalidadPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/FormularioEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/MainPage.xaml
SW1_ISO9126_FUZZY/Vistas/SeleccionMetricasPage.xaml
SW1_ISO9126_FUZZY/Vistas/VistaPreviaFormularioEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml
SW1_ISO9126_FUZZY/Vistas/VistaPreviaSeleccionMetricaPage.xaml.cs

Calculadas formulas previas a calculo difuso
Creado debug para todos las formulas previas al calculo difuso
Creada la conexion entre formulas y conexion previa al calculo difuso

Calculo formulas

---

SW1_ISO9126_FUZZY/Archivos/Reportes.cs
SW1_ISO9126_FUZZY/Vistas/EvaluacionCalidadPage.xaml
SW1_ISO9126_FUZZY/Vistas/EvaluacionCalidadPage.xaml.cs

- Se añadieron los parámetros de la evaluación en el reporte
- Se configuraron los parámetros de configuración para el pdf (fuente, tamaño letra)

Se configuraron los parámetros de la evaluación en el pdf

---

SW1_ISO9126_FUZZY/SW1_ISO9126_FUZZY.csproj
SW1_ISO9126_FUZZY/Vistas/MainPage.xaml.cs
SW1_ISO9126_FUZZY/Vistas/RegistroEvaluacionPage.xaml
SW1_ISO9126_FUZZY/Vistas/RegistroEvaluacionPage.xaml.cs
SW1_ISO9126_FUZZY/packages.config

Creado metodo para crear y  guardar evaluacion en JSON, con las respectivas validaciones.

Guardar cargar archivo
